---
- name: Install OpenJDK 11
  apt:
    name: openjdk-11-jdk
    state: present

- name: Install Jenkins
  yum:
    name: jenkins
    state: present

- name: Start Jenkins service
  service:
    name: jenkins
    state: started
    enabled: yes
