pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                // Checkout code from git and build
                git 'https://github.com/nagvadraj/IntellipaatCapstoneProject1.git'
                // Build Docker image
                sh 'docker build -t my-webapp .'
            }
        }
    }
}
