pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                // Checkout code from git and build
                git branch: 'main', url: 'https://github.com/nagvadraj/IntellipaatCapstoneProject1.git'
                // Build Docker image
                script {
                    docker.build('myweb-page')
                    docker.save('WORKSPACE/myweb-page}.tar')
                }
            }
        }
    }
}
