---
- name: Install Docker
  yum:
    name: docker
    state: present
    
- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
